import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/nav-bar";
import { auth0 } from "./lib/auth0";
import Link from "next/link";
import LandingPage from "./landing/page"; // 🏠 Importar la Landing Page


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Social App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth0.getSession();

  return (
    <html lang="en">
      <body className="antialiased flex h-screen bg-gray-900 text-white">
        {session ? (
          <>
            {/* ✅ Navbar flotante más ancho */}
            <Navbar session={session} />

            {/* ✅ Contenido principal con más margen */}
            <main className="flex-1 flex flex-col items-center bg-transparent text-white min-h-screen p-6">
              {children}
            </main>
          </>
        ) : (
          /* 🌍 Landing Page Minimalista */
          <div className="flex w-full h-screen">
            {/* ✅ Sección Izquierda con el Navbar */}
            <div className="w-1/3 bg-gray-950 p-10 flex flex-col justify-center items-center">
              <LandingPage /> {/* 📌 Aquí iría el componente de Landing */}
            </div>

            {/* ✅ Sección Derecha con el mensaje inspirador */}
            <div className="flex-1 flex flex-col justify-center items-center text-center text-white px-10">
              <h1 className="text-4xl font-bold">🌍 Comparte tus momentos con el mundo</h1>
              <p className="mt-4 text-lg text-gray-400">
                Conéctate con amigos y descubre nuevas historias cada día.
              </p>
            </div>
          </div>
        )}
      </body>
    </html>
  );
}

