import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/nav-bar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen`}
      >
        {/* Barra lateral */}
        <Navbar />
        {/* Contenido principal */}
        <main className="flex-1 flex justify-center items-center bg-gray-100">
          {children}
        </main>
      </body>
    </html>
  );
}

