import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/nav-bar";
import { auth0 } from "./lib/auth0";
import LandingPage from "./landing/page"; // 🏠 Importar la Landing Page

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Social App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth0.getSession();

  return (
    <html lang="en">
      <body className="antialiased flex h-screen bg-gray-900 text-white">
        {session ? (
          <>
            {/* ✅ Navbar responsive */}
            <Navbar session={session} />

            {/* ✅ Contenido principal responsivo */}
            <main className="flex-1 flex flex-col items-center bg-transparent text-white min-h-screen p-4 md:p-6">
              {children}
            </main>
          </>
        ) : (
          /* 🌍 Landing Page con diseño adaptable */
          <div className="flex flex-col md:flex-row w-full h-screen">
            {/* ✅ Sección Izquierda con el Navbar (oculta en móvil) */}
            <div className="hidden md:flex md:w-1/3 bg-gray-950 p-10 flex-col justify-center items-center">
              <LandingPage />
            </div>

            {/* ✅ Sección Derecha con el mensaje inspirador */}
            <div className="flex-1 flex flex-col justify-center items-center text-center text-white px-6 md:px-10">
              <h1 className="text-3xl md:text-4xl font-bold">🌍 Comparte tus momentos con el mundo</h1>
              <p className="mt-4 text-lg text-gray-400">
                Conéctate con amigos y descubre nuevas historias cada día.
              </p>

              {/* ✅ Botón de login centrado en móviles */}
              <div className="mt-6 md:hidden">
                <LandingPage />
              </div>
            </div>
          </div>
        )}
      </body>
    </html>
  );
}
